### ISSUE TITLE
Add more languages support !

### ISSUE THREAD

**Issue by danymat** [danymat/neogen#34]
Hello, in effort to target more users and improve the plugin, I will add more languages support than those currently in place.

I use this survey to prioritize support: https://insights.stackoverflow.com/survey/2021#technology-most-popular-technologies 

This is currently in TODO:

- [x] Rust (new support)
- [x] JavaScript/Typescript (add support for missing types)
- [x] Java (add support for missing types)
- [x] C# (new support)
- [x] Python (add support for missing types)
- [x] C++ (add support for missing types)
- [x] PHP (new support)
- [x] C (add support for missing types)
- [x] Go (new support)
- [x] Ruby (new support)
- [x] Bash (new support)
- [x] Kotlin (new support kdoc) 
- [ ] Groovy (new support)

**Comment by axieax** [comment]
As one of the users potentially migrating from [vim-doge](https://github.com/kkoomen/vim-doge), it would be awesome to see support for some of the popular languages supported there but not here, such as Bash, Groovy and Ruby. I haven't tested this, but does the JavaScript support work for Typescript, JavaScript-React and TypeScript-React as well?

**Comment by danymat** [comment]
Hello ! 

You right, I will add support for these 3 new languages (that reminds me of a reddit post that needs ruby support with [YARDOC](https://yardoc.org/index.html) convention)

Typescript is already implemented, as well as Javascript. JSX and TSX should work with these annotation conventions, I should just link them to their respective main languages (JS and TS).

**Comment by danymat** [comment]
> JSX and TSX should work with these annotation conventions, I should just link them to their respective main languages (JS and TS).

Added support for it with latest commit

**Comment by axieax** [comment]
Thanks!! I've just had a play around with both plugins and I've got to say I prefer vim-doge atm, mainly because of the more verbose templating that it provides (please see below for some examples). Thanks for the quick reply and changes tho :)

## Some Examples

> top: vim-doge
>bottom: neogen

- JS

![image](https://user-images.githubusercontent.com/62098008/151662720-5384eb82-0762-4aef-8c11-0380ddba007d.png)

- TS

![image](https://user-images.githubusercontent.com/62098008/151662790-5fa29880-f21f-4111-9bac-3ddb343ce8c0.png)

- Java

![image](https://user-images.githubusercontent.com/62098008/151662812-c39e99c0-f869-433a-a55e-4477c4e12315.png)

- Python

![image](https://user-images.githubusercontent.com/62098008/151662901-862cedfe-abb1-4c05-9425-f81732ecb722.png)

- Rust

![image](https://user-images.githubusercontent.com/62098008/151662933-64eb125c-76bd-4f42-84c3-d7d695808935.png)

- Lua

![image](https://user-images.githubusercontent.com/62098008/151663010-37f6199b-0cd8-4640-ab50-35c0040f7c64.png)

- C (and should be similar for C++)

![image](https://user-images.githubusercontent.com/62098008/151663054-6b4beab4-22ea-4e4c-8f11-bb5f3961b33f.png)

**Comment by danymat** [comment]
> I'll probably have to use both of them for now, unless there is a way to generate templates similar to vim-doge (mostly personal preference, with the [TEXT] being useful as reminders for fields to fill in).

I also wanted to support that, but I don"t really know how to do it properly. I wanted to use ext marks, as it allows me to write things without modifying the buffer. But I have to wait until we have anti conceal support.

I think that vim-doge does write the [TEXT] inside the buffer though. If it's not a problem, maybe I can consider adding it

**Comment by axieax** [comment]
Oo I haven't heard about ext marks before but that seems promising. Alternatively, virtual text can perhaps be used to indicate what to put on each line.

Yeah vim-doge does write to the buffer. In most cases, navigating to the next [BLOCK] selects the whole thing and allows you to instantly change it. Although, sometimes it cannot be selected so I have to manually remove it with 'ca]'.

**Comment by danymat** [comment]
> Yeah vim-doge does write to the buffer. In most cases, navigating to the next [BLOCK] selects the whole thing and allows you to instantly change it. Although, sometimes it cannot be selected so I have to manually remove it with 'ca]'.

And are you okay with this way of doing this ? 

Virt texts and ext marks are not useful at the moment, until anti conceal is implemented sadly :'( so we would have to fallback to a "dirtier" process. 

If writing to the buffer is okay for you, I can take a look at this when I have time

**Comment by axieax** [comment]
Fair enough ahaha, writing to the buffer sounds good for now and would be a much appreciated feature! :)
Thanks!!

**Comment by ObserverOfTime** [comment]
Can you also add [Kdoc](https://kotlinlang.org/docs/kotlin-doc.html) for Kotlin? It's similar to javadoc.

**Comment by danymat** [comment]
> Can you also add [Kdoc](https://kotlinlang.org/docs/kotlin-doc.html) for Kotlin? It's similar to javadoc.

Added to the list !
