### ISSUE TITLE
(py) Add support for reST template

### ISSUE THREAD

**Issue by danymat** [danymat/neogen#46]
- https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

**Comment by equalis3r** [comment]
Hi @danymat Thanks again for this awesome plugin and your kindness in adding features. The features work with the case when one does not use typehint. However, when typehint is used:
```
def function(a: int, b: int) -> int:
    """

    :param a: 
    :type int: 
    :param b: 
    :type int: 
    :return: 
    :rtype: 
    """
```
This is the docstring generated. As you can see, it parses the typehint as the name of the type instead of the actual type. What is expected is:
```
def function(a: int, b: int) -> int:
    """

    :param a: 
    :type a: int
    :param b: 
    :type b: int
    :return: 
    :rtype: int
    """
```
For `google_docstrings` and `numpydoc`, the typehint is correctly parsed and generated.

**Comment by danymat** [comment]
Right, small mistake lol, sorry. I'm thinking it right now

**Comment by danymat** [comment]
@equalis3r, can you try again ?

**Comment by equalis3r** [comment]
@danymat It works flawlessly now. Many thanks to you.
